version: '3.8'
services:
  es-api:
    container_name: es-api
    build:
      dockerfile: es-api/Dockerfile.dev
    restart: always
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USER=username
      - ES_PASS=password
    ports:
      - "6003:6002"
    expose:
      - "6003"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./es-api:/app/es-api

  pg-api:
    container_name: pg-api
    build:
      dockerfile: pg-api/Dockerfile.dev
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database
    ports:
      - "6002:6002"
    expose:
      - "6002"
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./pg-api:/app/pg-api

  database:
    container_name: postgres
    image: ghcr.io/stac-utils/pgstac:v0.6.6
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    ports:
      - "5433:5432"
    command: postgres -N 500

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  esdata: